[package]
name = "type-fields-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.51"
syn = { version = "2.0.4", features = ["full", "visit-mut"] }
quote = "1.0.23"
convert_case = "0.6.0"
