[package]
name = "type-fields-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.4", features = ["full"] }

proc-macro2 = "1.0.51"
quote = "1.0.23"
